---
- name: Try to move OU
  hosts: "{{ delegate_to }}"
  gather_facts: false

  tasks:
    - name: Add current VM to host
      microsoft.ad.computer:
        identity: "{{ host_name }}"
        path: "{{ domain_ou }}"
        state: present
        domain_username: "{{ domain_username }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
