---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: false

  #roles:
  #  - vm-create

  post_tasks:
    - name: Add current VM to host
      ansible.builtin.add_host:
        name: "{{ vm_name }}.{{ domain }}"
        groups: created_vm

- name: Create a VM from a template
  hosts: created_vm
  tasks:
    - name: Ensure windows host is reachable
      ansible.windows.win_ping:
