- name: Create a VM from a template
  hosts: localhost
  gather_facts: false
  tasks:
  #roles:
  #  - vm-create

  post_tasks:
    - add_host:
        hostname: "{{ vm_name }}.{{ domain }}"
        groups: foogroup

    - debug:
        var: ansible_play_hosts

- hosts: foogroup
  gather_facts: false
  connection: local
  vars:
  ansible_connection: winrm
  ansible_winrm_transport: kerberos
  ansible_port: 5985

  tasks:
    - name: Test KERB
      ansible.windows.win_ping:

    - debug:
        msg: I was added successfully!
