---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: false

  #roles:
  #  - vm-create

  post_tasks:
    - name: Add current VM to host
      ansible.builtin.add_host:
        name: "{{ vm_name }}.{{ domain }}"
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_port: 5985
        groups: created_vm

- name: Create a VM from a template
  hosts: created_vm
  vars:
    domain_upper: "{{ your_username.split('@')[1] | upper }}"
    user_name: "{{ your_username.split('@')[0] | lower }}"
    ansible_user: "{{ user_name }}@{{ domain_upper }}"
    ansible_password: "{{ your_password }}"
    #ansible_winrm_kerberos_delegation: true
  tasks:
    - name: Ensure windows host is reachable
      ansible.windows.win_ping:
    - name: Install the Visual C thingy
      ansible.windows.win_package:
        path: https://aka.ms/vs/17/release/vc_redist.x64.exe
        product_id: "{59CED48F-EBFE-480C-8A38-FC079C2BEC0F}"
        arguments: /install /passive /norestart
    - name: Install the Visual C thingy
      ansible.windows.win_package:
        path: https://aka.ms/vs/17/release/vc_redist.x86.exe
        product_id: "{0C3457A0-3DCE-4A33-BEF0-9B528C557771}"
        arguments: /install /passive /norestart
