- name: Create a VM from a template
  hosts: localhost
  gather_facts: false
  #roles:
  #  - vm-create

  post_tasks:
- name: Add host to group 'just_created' with variable foo=42
  ansible.builtin.add_host:
    hostname: "{{ vm_name }}.{{ domain }}"
    groups: new_vm
#   post_tasks:
#     - add_host:
#       hostname: "{{ vm_name }}.{{ domain }}"
#       groups: new_vm

- name: Test Winrm
  hosts: new_vm
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_port: 5985
- name: Ensure windows host is reachable
  ansible.windows.win_ping:
