- hosts: localhost
  gather_facts: false
  tasks:
    #roles:
    #  - vm-create
    #  post_tasks:
    - name: Test Winrm
      ansible.builtin.add_host:
        ansible_host: "{{ vm_name }}.{{ domain }}"
        groups: new_vm
        ansible_connection: winrm
        ansible_winrm_transport: kerberos
        ansible_port: 5985

  post_tasks:
- hosts: new_vm
  gather_facts: false
  name: Ensure windows host is reachable
  ansible.windows.win_ping:
