---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: false

  #roles:
  #  - vm-create

  post_tasks:
    - name: Add current VM to host
      ansible.builtin.add_host:
        name: "{{ vm_name }}.{{ domain_name }}"
        groups: created_vm
