- name: Create a VM from a template
  hosts: localhost
  gather_facts: false
  vars:
  roles:
    - vm-create
  post_tasks:
    - add_host:
      hostname: "{{ vm_name }}.{{ domain }}"
      groups: new_vm

- name: Test Winrm
  hosts: new_vm
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_port: 5986
- name: Ensure windows host is reachable
  ansible.windows.win_ping:
