---
# tasks file for vm-create
- name: Check if virtual machine exists
  community.vmware.vmware_guest_info:
    validate_certs: "{{ validate_certs | default('false') }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ your_username }}"
    password: "{{ your_password }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    folder: "{{ vm_folder }}"
  ignore_errors: true
  throttle: 1
  register: vm_exists

- name: Print if virtual machine exists
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
  when: vm_exists is defined

- name: Print if virtual machine does ot exists
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
  when: vm_exists is not defined

- name: Print if virtual machine DESTRUCTIVE
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
  when: destructive == True and vm_exists is defined
