---
# tasks file for vm-create
- name: Check if virtual machine exists
  community.vmware.vmware_guest_info:
    validate_certs: "{{ validate_certs | default('false') }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vmware_password }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    folder: "{{ vm_folder }}"
  ignore_errors: true
  throttle: 1
  register: vm_exists
  when: destructive is not defined or not destructive
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
