- name: Copy file to vm
  community.vmware.vmware_guest_file_operation:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ your_username }}"
    password: "{{ your_password }}"
    validate_certs: false
    vm_id: "{{ vm_name }}"
    vm_username: "{{ your_username }}"
    vm_password: "{{ your_password }}"
    copy:
      src: "roles/files/setup.ps1"
      dest: C:\Temp\setup.ps1
      overwrite: true

- name: Run the Powershell script to generate a new cert and enable 5986 port in firewall
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ your_username }}"
    password: "{{ your_password }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    vm_id: "{{ vm_name }}"
    validate_certs: false
    vm_username: "{{ your_username }}"
    vm_password: "{{ your_password }}"
    vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
    vm_shell_args: '-ExecutionPolicy Unrestricted -File C:\Temp\setup.ps1'
    wait_for_process: true
