---
# tasks file for vm-create
- name: Check if virtual machine exists
  community.vmware.vmware_guest_info:
    validate_certs: "{{ validate_certs | default('false') }}"
    hostname: "{{ vcenter_hostname }}"
    username: "{{ your_username }}"
    password: "{{ your_password }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
  ignore_errors: true
  throttle: 1
  register: vm_exists

- name: Print if virtual machine exists
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
  when: vm_exists is defined

- name: Print if virtual machine does ot exists
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
  when: vm_exists is not defined

- name: Print if virtual machine DESTRUCTIVE
  delegate_to: localhost
  ansible.builtin.debug:
    msg: "{{ destructive }} {{ vm_exists }}"
  when: destructive == "True" and vm_exists is defined

- name: Remove virtual machine from inventory
  community.vmware.vmware_guest:
    validate_certs: false
    hostname: "{{ vcenter_hostname }}"
    username: "{{ your_username }}"
    password: "{{ your_username }}"
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    folder: "{{ vm_folder }}"
    state: absent
    state_change_timeout: 120
    force: true
  delegate_to: localhost
  throttle: 1
  when: destructive == True and vm_exists is defined
  debug:
    msg: "{{ destructive }} {{ vm_exists }}"
